import { Roboto } from 'next/font/google'
import { TotalTickets } from '@/entities/basket'
import { Header } from '@/shared/ui/header'
import { Footer } from '@/shared/ui/footer'
import { StoreProvider } from './store'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <StoreProvider>
                <body className={roboto.className}>
                    <Header pageTitle="Билетопоиск" sideInfo={<TotalTickets />} />
                    <main>{children}</main>
                    <div id="dropdown"></div>
                    <div id="modal"></div>
                    <Footer />
                </body>
            </StoreProvider>
        </html>
    )
}
